title: zjuthesis
description: 浙江大学毕业论文 LaTeX 模板
theme: jekyll-theme-slate
show_downloads: true
github:
  zip_url: https://github.com/TheNetAdmin/zjuthesis/releases/latest
  tar_url: https://github.com/TheNetAdmin/zjuthesis/releases/latest
